[package]
name = "rpi-mqtt-gpio"
version = "0.1.3"
edition = "2021"

[dependencies]
gpio-cdev = "0.4"
rumqttc = "0.20"
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[profile.release]
strip = true
