mqtt:
  name: rpi-mqtt-gpio
  host: 192.168.1.1
  port: 1883
  qos: 1
  keep_alive: 5
  clean_session: false
  retain: false
  cap: 10

digital_outputs:
  # Output to disable the heatpump
  - name: i1
    gpio: 5
    mqtt_topic: "heatpump/output/i1"
    mqtt_topic_set: "heatpump/output/i1/set"
    mqtt_state_high: "ON"
    mqtt_state_low: "OFF"
    initial_state: "OFF"

    # An availability topic is useful to notify consumers on whether the switch is available or not
    # based on whether the daemon is running. In particular, home assistant uses this to show an
    # unavailable state in case the daemon is not running.
    # See: https://www.home-assistant.io/integrations/switch.mqtt/#availability
    availability_topic: "rpi-mqtt-gpio/status"
    payload_available: "online"
    payload_not_available: "offline"


  # Output to enable PV mode (full steam)
  - name: i3
    gpio: 22
    mqtt_topic: "heatpump/output/i3"
    mqtt_topic_set: "heatpump/output/i3/set"
